[profile.default]
src = "src"
out = "out"

libs = ['node_modules', 'lib']
remappings = [
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip',
    '@chainlink/contracts/=node_modules/@chainlink/contracts/',
    '@openzeppelin/contracts/=node_modules/openzeppelin/contracts/',
]
